#pragma warning disable
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DurableRpc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from DurableRpc.proto</summary>
public static partial class DurableRpcReflection {

  #region Descriptor
  /// <summary>File descriptor for DurableRpc.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DurableRpcReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChBEdXJhYmxlUnBjLnByb3RvGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1w",
          "LnByb3RvIuoBCg1DbGllbnRSZXF1ZXN0EiEKBHR5cGUYASABKA4yEy5DbGll",
          "bnRSZXF1ZXN0LlR5cGUSJgoEYXJncxgCIAMoCzIYLkNsaWVudFJlcXVlc3Qu",
          "QXJnc0VudHJ5GjkKCUFyZ3NFbnRyeRILCgNrZXkYASABKAkSGwoFdmFsdWUY",
          "AiABKAsyDC5SZXF1ZXN0RGF0YToCOAEiUwoEVHlwZRIKCgZTdGF0dXMQABIK",
          "CgZDcmVhdGUQARINCglTZW5kRXZlbnQQAhINCglUZXJtaW5hdGUQAxIKCgZS",
          "ZXdpbmQQBBIJCgVQdXJnZRAFIokBCg5DbGllbnRSZXNwb25zZRImCgZyZXN1",
          "bHQYASABKA4yFi5DbGllbnRSZXNwb25zZS5SZXN1bHQSDQoFZXJyb3IYAiAB",
          "KAwSGwoEZGF0YRgDIAEoCzINLlJlc3BvbnNlRGF0YSIjCgZSZXN1bHQSDQoJ",
          "Q29tcGxldGVkEAASCgoGRmFpbGVkEAEiuAEKC1JlcXVlc3REYXRhEhAKBnN0",
          "cmluZxgBIAEoCUgAEg8KBWJ5dGVzGAIgASgMSAASDgoEYm9vbBgDIAEoCEgA",
          "Eg0KA2ludBgEIAEoEkgAEi8KCXRpbWVzdGFtcBgFIAEoCzIaLmdvb2dsZS5w",
          "cm90b2J1Zi5UaW1lc3RhbXBIABIuChFjb2xsZWN0aW9uX3N0cmluZxgGIAEo",
          "CzIRLkNvbGxlY3Rpb25TdHJpbmdIAEIGCgRkYXRhIoYBCgxSZXNwb25zZURh",
          "dGESKwoGc3RhdHVzGAEgASgLMhsuRHVyYWJsZU9yY2hlc3RyYXRpb25TdGF0",
          "dXMSLAoRc3RhdHVzX2NvbGxlY3Rpb24YAiABKAsyES5TdGF0dXNDb2xsZWN0",
          "aW9uEg4KBnN0cmluZxgDIAEoCRILCgNpbnQYBCABKBIiIgoQQ29sbGVjdGlv",
          "blN0cmluZxIOCgZzdHJpbmcYASADKAkiWQoQU3RhdHVzQ29sbGVjdGlvbhIq",
          "CgVzdGF0ZRgBIAMoCzIbLkR1cmFibGVPcmNoZXN0cmF0aW9uU3RhdHVzEhkK",
          "EWNvbnRpbnVhdGlvblRva2VuGAIgASgJIvoBChpEdXJhYmxlT3JjaGVzdHJh",
          "dGlvblN0YXR1cxIMCgRuYW1lGAEgASgJEgoKAmlkGAIgASgJEi8KC2NyZWF0",
          "ZWRUaW1lGAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIzCg9s",
          "YXN0VXBkYXRlZFRpbWUYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0",
          "YW1wEg0KBWlucHV0GAUgASgJEg4KBm91dHB1dBgGIAEoCRIWCg5ydW50aW1l",
          "X3N0YXR1cxgHIAMoCRIUCgxjdXN0b21TdGF0dXMYCCABKAkSDwoHaGlzdG9y",
          "eRgJIAMoCTJCCgpEdXJhYmxlUnBjEjQKD0NsaWVudE9wZXJhdGlvbhIOLkNs",
          "aWVudFJlcXVlc3QaDy5DbGllbnRSZXNwb25zZSIAYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ClientRequest), global::ClientRequest.Parser, new[]{ "Type", "Args" }, null, new[]{ typeof(global::ClientRequest.Types.Type) }, new pbr::GeneratedClrTypeInfo[] { null, }),
          new pbr::GeneratedClrTypeInfo(typeof(global::ClientResponse), global::ClientResponse.Parser, new[]{ "Result", "Error", "Data" }, null, new[]{ typeof(global::ClientResponse.Types.Result) }, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RequestData), global::RequestData.Parser, new[]{ "String", "Bytes", "Bool", "Int", "Timestamp", "CollectionString" }, new[]{ "Data" }, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ResponseData), global::ResponseData.Parser, new[]{ "Status", "StatusCollection", "String", "Int" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CollectionString), global::CollectionString.Parser, new[]{ "String" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::StatusCollection), global::StatusCollection.Parser, new[]{ "State", "ContinuationToken" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::DurableOrchestrationStatus), global::DurableOrchestrationStatus.Parser, new[]{ "Name", "Id", "CreatedTime", "LastUpdatedTime", "Input", "Output", "RuntimeStatus", "CustomStatus", "History" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ClientRequest : pb::IMessage<ClientRequest> {
  private static readonly pb::MessageParser<ClientRequest> _parser = new pb::MessageParser<ClientRequest>(() => new ClientRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ClientRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DurableRpcReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientRequest(ClientRequest other) : this() {
    type_ = other.type_;
    args_ = other.args_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientRequest Clone() {
    return new ClientRequest(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::ClientRequest.Types.Type type_ = 0;
  /// <summary>
  /// Type of client request.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ClientRequest.Types.Type Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "args" field.</summary>
  public const int ArgsFieldNumber = 2;
  private static readonly pbc::MapField<string, global::RequestData>.Codec _map_args_codec
      = new pbc::MapField<string, global::RequestData>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForMessage(18, global::RequestData.Parser), 18);
  private readonly pbc::MapField<string, global::RequestData> args_ = new pbc::MapField<string, global::RequestData>();
  /// <summary>
  /// properties
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::MapField<string, global::RequestData> Args {
    get { return args_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ClientRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ClientRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (!Args.Equals(other.Args)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != 0) hash ^= Type.GetHashCode();
    hash ^= Args.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Type != 0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    args_.WriteTo(output, _map_args_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Type != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    size += args_.CalculateSize(_map_args_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ClientRequest other) {
    if (other == null) {
      return;
    }
    if (other.Type != 0) {
      Type = other.Type;
    }
    args_.Add(other.args_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::ClientRequest.Types.Type) input.ReadEnum();
          break;
        }
        case 18: {
          args_.AddEntriesFrom(input, _map_args_codec);
          break;
        }
      }
    }
  }

  #region Nested types
  /// <summary>Container for nested types declared in the ClientRequest message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public enum Type {
      [pbr::OriginalName("Status")] Status = 0,
      [pbr::OriginalName("Create")] Create = 1,
      [pbr::OriginalName("SendEvent")] SendEvent = 2,
      [pbr::OriginalName("Terminate")] Terminate = 3,
      [pbr::OriginalName("Rewind")] Rewind = 4,
      [pbr::OriginalName("Purge")] Purge = 5,
    }

  }
  #endregion

}

public sealed partial class ClientResponse : pb::IMessage<ClientResponse> {
  private static readonly pb::MessageParser<ClientResponse> _parser = new pb::MessageParser<ClientResponse>(() => new ClientResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ClientResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DurableRpcReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientResponse(ClientResponse other) : this() {
    result_ = other.result_;
    error_ = other.error_;
    data_ = other.data_ != null ? other.data_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientResponse Clone() {
    return new ClientResponse(this);
  }

  /// <summary>Field number for the "result" field.</summary>
  public const int ResultFieldNumber = 1;
  private global::ClientResponse.Types.Result result_ = 0;
  /// <summary>
  /// 
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ClientResponse.Types.Result Result {
    get { return result_; }
    set {
      result_ = value;
    }
  }

  /// <summary>Field number for the "error" field.</summary>
  public const int ErrorFieldNumber = 2;
  private pb::ByteString error_ = pb::ByteString.Empty;
  /// <summary>
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Error {
    get { return error_; }
    set {
      error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 3;
  private global::ResponseData data_;
  /// <summary>
  /// TODO: not bytes
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ResponseData Data {
    get { return data_; }
    set {
      data_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ClientResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ClientResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Result != other.Result) return false;
    if (Error != other.Error) return false;
    if (!object.Equals(Data, other.Data)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Result != 0) hash ^= Result.GetHashCode();
    if (Error.Length != 0) hash ^= Error.GetHashCode();
    if (data_ != null) hash ^= Data.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Result != 0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Result);
    }
    if (Error.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(Error);
    }
    if (data_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Result != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
    }
    if (Error.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Error);
    }
    if (data_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ClientResponse other) {
    if (other == null) {
      return;
    }
    if (other.Result != 0) {
      Result = other.Result;
    }
    if (other.Error.Length != 0) {
      Error = other.Error;
    }
    if (other.data_ != null) {
      if (data_ == null) {
        Data = new global::ResponseData();
      }
      Data.MergeFrom(other.Data);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Result = (global::ClientResponse.Types.Result) input.ReadEnum();
          break;
        }
        case 18: {
          Error = input.ReadBytes();
          break;
        }
        case 26: {
          if (data_ == null) {
            Data = new global::ResponseData();
          }
          input.ReadMessage(Data);
          break;
        }
      }
    }
  }

  #region Nested types
  /// <summary>Container for nested types declared in the ClientResponse message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public enum Result {
      [pbr::OriginalName("Completed")] Completed = 0,
      [pbr::OriginalName("Failed")] Failed = 1,
    }

  }
  #endregion

}

/// <summary>
/// Used to encapsulate request data which could be a variety of types
/// </summary>
public sealed partial class RequestData : pb::IMessage<RequestData> {
  private static readonly pb::MessageParser<RequestData> _parser = new pb::MessageParser<RequestData>(() => new RequestData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<RequestData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DurableRpcReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RequestData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RequestData(RequestData other) : this() {
    switch (other.DataCase) {
      case DataOneofCase.String:
        String = other.String;
        break;
      case DataOneofCase.Bytes:
        Bytes = other.Bytes;
        break;
      case DataOneofCase.Bool:
        Bool = other.Bool;
        break;
      case DataOneofCase.Int:
        Int = other.Int;
        break;
      case DataOneofCase.Timestamp:
        Timestamp = other.Timestamp.Clone();
        break;
      case DataOneofCase.CollectionString:
        CollectionString = other.CollectionString.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RequestData Clone() {
    return new RequestData(this);
  }

  /// <summary>Field number for the "string" field.</summary>
  public const int StringFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string String {
    get { return dataCase_ == DataOneofCase.String ? (string) data_ : ""; }
    set {
      data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      dataCase_ = DataOneofCase.String;
    }
  }

  /// <summary>Field number for the "bytes" field.</summary>
  public const int BytesFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Bytes {
    get { return dataCase_ == DataOneofCase.Bytes ? (pb::ByteString) data_ : pb::ByteString.Empty; }
    set {
      data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      dataCase_ = DataOneofCase.Bytes;
    }
  }

  /// <summary>Field number for the "bool" field.</summary>
  public const int BoolFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Bool {
    get { return dataCase_ == DataOneofCase.Bool ? (bool) data_ : false; }
    set {
      data_ = value;
      dataCase_ = DataOneofCase.Bool;
    }
  }

  /// <summary>Field number for the "int" field.</summary>
  public const int IntFieldNumber = 4;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long Int {
    get { return dataCase_ == DataOneofCase.Int ? (long) data_ : 0L; }
    set {
      data_ = value;
      dataCase_ = DataOneofCase.Int;
    }
  }

  /// <summary>Field number for the "timestamp" field.</summary>
  public const int TimestampFieldNumber = 5;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
    get { return dataCase_ == DataOneofCase.Timestamp ? (global::Google.Protobuf.WellKnownTypes.Timestamp) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Timestamp;
    }
  }

  /// <summary>Field number for the "collection_string" field.</summary>
  public const int CollectionStringFieldNumber = 6;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::CollectionString CollectionString {
    get { return dataCase_ == DataOneofCase.CollectionString ? (global::CollectionString) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.CollectionString;
    }
  }

  private object data_;
  /// <summary>Enum of possible cases for the "data" oneof.</summary>
  public enum DataOneofCase {
    None = 0,
    String = 1,
    Bytes = 2,
    Bool = 3,
    Int = 4,
    Timestamp = 5,
    CollectionString = 6,
  }
  private DataOneofCase dataCase_ = DataOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DataOneofCase DataCase {
    get { return dataCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearData() {
    dataCase_ = DataOneofCase.None;
    data_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as RequestData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(RequestData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (String != other.String) return false;
    if (Bytes != other.Bytes) return false;
    if (Bool != other.Bool) return false;
    if (Int != other.Int) return false;
    if (!object.Equals(Timestamp, other.Timestamp)) return false;
    if (!object.Equals(CollectionString, other.CollectionString)) return false;
    if (DataCase != other.DataCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (dataCase_ == DataOneofCase.String) hash ^= String.GetHashCode();
    if (dataCase_ == DataOneofCase.Bytes) hash ^= Bytes.GetHashCode();
    if (dataCase_ == DataOneofCase.Bool) hash ^= Bool.GetHashCode();
    if (dataCase_ == DataOneofCase.Int) hash ^= Int.GetHashCode();
    if (dataCase_ == DataOneofCase.Timestamp) hash ^= Timestamp.GetHashCode();
    if (dataCase_ == DataOneofCase.CollectionString) hash ^= CollectionString.GetHashCode();
    hash ^= (int) dataCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (dataCase_ == DataOneofCase.String) {
      output.WriteRawTag(10);
      output.WriteString(String);
    }
    if (dataCase_ == DataOneofCase.Bytes) {
      output.WriteRawTag(18);
      output.WriteBytes(Bytes);
    }
    if (dataCase_ == DataOneofCase.Bool) {
      output.WriteRawTag(24);
      output.WriteBool(Bool);
    }
    if (dataCase_ == DataOneofCase.Int) {
      output.WriteRawTag(32);
      output.WriteSInt64(Int);
    }
    if (dataCase_ == DataOneofCase.Timestamp) {
      output.WriteRawTag(42);
      output.WriteMessage(Timestamp);
    }
    if (dataCase_ == DataOneofCase.CollectionString) {
      output.WriteRawTag(50);
      output.WriteMessage(CollectionString);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (dataCase_ == DataOneofCase.String) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(String);
    }
    if (dataCase_ == DataOneofCase.Bytes) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Bytes);
    }
    if (dataCase_ == DataOneofCase.Bool) {
      size += 1 + 1;
    }
    if (dataCase_ == DataOneofCase.Int) {
      size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Int);
    }
    if (dataCase_ == DataOneofCase.Timestamp) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
    }
    if (dataCase_ == DataOneofCase.CollectionString) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(CollectionString);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(RequestData other) {
    if (other == null) {
      return;
    }
    switch (other.DataCase) {
      case DataOneofCase.String:
        String = other.String;
        break;
      case DataOneofCase.Bytes:
        Bytes = other.Bytes;
        break;
      case DataOneofCase.Bool:
        Bool = other.Bool;
        break;
      case DataOneofCase.Int:
        Int = other.Int;
        break;
      case DataOneofCase.Timestamp:
        if (Timestamp == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
        break;
      case DataOneofCase.CollectionString:
        if (CollectionString == null) {
          CollectionString = new global::CollectionString();
        }
        CollectionString.MergeFrom(other.CollectionString);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          String = input.ReadString();
          break;
        }
        case 18: {
          Bytes = input.ReadBytes();
          break;
        }
        case 24: {
          Bool = input.ReadBool();
          break;
        }
        case 32: {
          Int = input.ReadSInt64();
          break;
        }
        case 42: {
          global::Google.Protobuf.WellKnownTypes.Timestamp subBuilder = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          if (dataCase_ == DataOneofCase.Timestamp) {
            subBuilder.MergeFrom(Timestamp);
          }
          input.ReadMessage(subBuilder);
          Timestamp = subBuilder;
          break;
        }
        case 50: {
          global::CollectionString subBuilder = new global::CollectionString();
          if (dataCase_ == DataOneofCase.CollectionString) {
            subBuilder.MergeFrom(CollectionString);
          }
          input.ReadMessage(subBuilder);
          CollectionString = subBuilder;
          break;
        }
      }
    }
  }

}

/// <summary>
/// Used to encapsulate response data which could be a variety of types
/// </summary>
public sealed partial class ResponseData : pb::IMessage<ResponseData> {
  private static readonly pb::MessageParser<ResponseData> _parser = new pb::MessageParser<ResponseData>(() => new ResponseData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ResponseData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DurableRpcReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ResponseData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ResponseData(ResponseData other) : this() {
    status_ = other.status_ != null ? other.status_.Clone() : null;
    statusCollection_ = other.statusCollection_ != null ? other.statusCollection_.Clone() : null;
    string_ = other.string_;
    int_ = other.int_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ResponseData Clone() {
    return new ResponseData(this);
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 1;
  private global::DurableOrchestrationStatus status_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DurableOrchestrationStatus Status {
    get { return status_; }
    set {
      status_ = value;
    }
  }

  /// <summary>Field number for the "status_collection" field.</summary>
  public const int StatusCollectionFieldNumber = 2;
  private global::StatusCollection statusCollection_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::StatusCollection StatusCollection {
    get { return statusCollection_; }
    set {
      statusCollection_ = value;
    }
  }

  /// <summary>Field number for the "string" field.</summary>
  public const int StringFieldNumber = 3;
  private string string_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string String {
    get { return string_; }
    set {
      string_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "int" field.</summary>
  public const int IntFieldNumber = 4;
  private long int_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long Int {
    get { return int_; }
    set {
      int_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ResponseData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ResponseData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Status, other.Status)) return false;
    if (!object.Equals(StatusCollection, other.StatusCollection)) return false;
    if (String != other.String) return false;
    if (Int != other.Int) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (status_ != null) hash ^= Status.GetHashCode();
    if (statusCollection_ != null) hash ^= StatusCollection.GetHashCode();
    if (String.Length != 0) hash ^= String.GetHashCode();
    if (Int != 0L) hash ^= Int.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (status_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Status);
    }
    if (statusCollection_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(StatusCollection);
    }
    if (String.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(String);
    }
    if (Int != 0L) {
      output.WriteRawTag(32);
      output.WriteSInt64(Int);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (status_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Status);
    }
    if (statusCollection_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(StatusCollection);
    }
    if (String.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(String);
    }
    if (Int != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Int);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ResponseData other) {
    if (other == null) {
      return;
    }
    if (other.status_ != null) {
      if (status_ == null) {
        Status = new global::DurableOrchestrationStatus();
      }
      Status.MergeFrom(other.Status);
    }
    if (other.statusCollection_ != null) {
      if (statusCollection_ == null) {
        StatusCollection = new global::StatusCollection();
      }
      StatusCollection.MergeFrom(other.StatusCollection);
    }
    if (other.String.Length != 0) {
      String = other.String;
    }
    if (other.Int != 0L) {
      Int = other.Int;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (status_ == null) {
            Status = new global::DurableOrchestrationStatus();
          }
          input.ReadMessage(Status);
          break;
        }
        case 18: {
          if (statusCollection_ == null) {
            StatusCollection = new global::StatusCollection();
          }
          input.ReadMessage(StatusCollection);
          break;
        }
        case 26: {
          String = input.ReadString();
          break;
        }
        case 32: {
          Int = input.ReadSInt64();
          break;
        }
      }
    }
  }

}

/// <summary>
/// Used to encapsulate collection string
/// </summary>
public sealed partial class CollectionString : pb::IMessage<CollectionString> {
  private static readonly pb::MessageParser<CollectionString> _parser = new pb::MessageParser<CollectionString>(() => new CollectionString());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<CollectionString> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DurableRpcReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public CollectionString() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public CollectionString(CollectionString other) : this() {
    string_ = other.string_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public CollectionString Clone() {
    return new CollectionString(this);
  }

  /// <summary>Field number for the "string" field.</summary>
  public const int StringFieldNumber = 1;
  private static readonly pb::FieldCodec<string> _repeated_string_codec
      = pb::FieldCodec.ForString(10);
  private readonly pbc::RepeatedField<string> string_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<string> String {
    get { return string_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as CollectionString);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(CollectionString other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!string_.Equals(other.string_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= string_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    string_.WriteTo(output, _repeated_string_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += string_.CalculateSize(_repeated_string_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(CollectionString other) {
    if (other == null) {
      return;
    }
    string_.Add(other.string_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          string_.AddEntriesFrom(input, _repeated_string_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class StatusCollection : pb::IMessage<StatusCollection> {
  private static readonly pb::MessageParser<StatusCollection> _parser = new pb::MessageParser<StatusCollection>(() => new StatusCollection());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<StatusCollection> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DurableRpcReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public StatusCollection() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public StatusCollection(StatusCollection other) : this() {
    state_ = other.state_.Clone();
    continuationToken_ = other.continuationToken_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public StatusCollection Clone() {
    return new StatusCollection(this);
  }

  /// <summary>Field number for the "state" field.</summary>
  public const int StateFieldNumber = 1;
  private static readonly pb::FieldCodec<global::DurableOrchestrationStatus> _repeated_state_codec
      = pb::FieldCodec.ForMessage(10, global::DurableOrchestrationStatus.Parser);
  private readonly pbc::RepeatedField<global::DurableOrchestrationStatus> state_ = new pbc::RepeatedField<global::DurableOrchestrationStatus>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::DurableOrchestrationStatus> State {
    get { return state_; }
  }

  /// <summary>Field number for the "continuationToken" field.</summary>
  public const int ContinuationTokenFieldNumber = 2;
  private string continuationToken_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string ContinuationToken {
    get { return continuationToken_; }
    set {
      continuationToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as StatusCollection);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(StatusCollection other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!state_.Equals(other.state_)) return false;
    if (ContinuationToken != other.ContinuationToken) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= state_.GetHashCode();
    if (ContinuationToken.Length != 0) hash ^= ContinuationToken.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    state_.WriteTo(output, _repeated_state_codec);
    if (ContinuationToken.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(ContinuationToken);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += state_.CalculateSize(_repeated_state_codec);
    if (ContinuationToken.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ContinuationToken);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(StatusCollection other) {
    if (other == null) {
      return;
    }
    state_.Add(other.state_);
    if (other.ContinuationToken.Length != 0) {
      ContinuationToken = other.ContinuationToken;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          state_.AddEntriesFrom(input, _repeated_state_codec);
          break;
        }
        case 18: {
          ContinuationToken = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class DurableOrchestrationStatus : pb::IMessage<DurableOrchestrationStatus> {
  private static readonly pb::MessageParser<DurableOrchestrationStatus> _parser = new pb::MessageParser<DurableOrchestrationStatus>(() => new DurableOrchestrationStatus());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<DurableOrchestrationStatus> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DurableRpcReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DurableOrchestrationStatus() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DurableOrchestrationStatus(DurableOrchestrationStatus other) : this() {
    name_ = other.name_;
    id_ = other.id_;
    createdTime_ = other.createdTime_ != null ? other.createdTime_.Clone() : null;
    lastUpdatedTime_ = other.lastUpdatedTime_ != null ? other.lastUpdatedTime_.Clone() : null;
    input_ = other.input_;
    output_ = other.output_;
    runtimeStatus_ = other.runtimeStatus_.Clone();
    customStatus_ = other.customStatus_;
    history_ = other.history_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DurableOrchestrationStatus Clone() {
    return new DurableOrchestrationStatus(this);
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 2;
  private string id_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "createdTime" field.</summary>
  public const int CreatedTimeFieldNumber = 3;
  private global::Google.Protobuf.WellKnownTypes.Timestamp createdTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Google.Protobuf.WellKnownTypes.Timestamp CreatedTime {
    get { return createdTime_; }
    set {
      createdTime_ = value;
    }
  }

  /// <summary>Field number for the "lastUpdatedTime" field.</summary>
  public const int LastUpdatedTimeFieldNumber = 4;
  private global::Google.Protobuf.WellKnownTypes.Timestamp lastUpdatedTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Google.Protobuf.WellKnownTypes.Timestamp LastUpdatedTime {
    get { return lastUpdatedTime_; }
    set {
      lastUpdatedTime_ = value;
    }
  }

  /// <summary>Field number for the "input" field.</summary>
  public const int InputFieldNumber = 5;
  private string input_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Input {
    get { return input_; }
    set {
      input_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "output" field.</summary>
  public const int OutputFieldNumber = 6;
  private string output_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Output {
    get { return output_; }
    set {
      output_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "runtime_status" field.</summary>
  public const int RuntimeStatusFieldNumber = 7;
  private static readonly pb::FieldCodec<string> _repeated_runtimeStatus_codec
      = pb::FieldCodec.ForString(58);
  private readonly pbc::RepeatedField<string> runtimeStatus_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<string> RuntimeStatus {
    get { return runtimeStatus_; }
  }

  /// <summary>Field number for the "customStatus" field.</summary>
  public const int CustomStatusFieldNumber = 8;
  private string customStatus_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string CustomStatus {
    get { return customStatus_; }
    set {
      customStatus_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "history" field.</summary>
  public const int HistoryFieldNumber = 9;
  private static readonly pb::FieldCodec<string> _repeated_history_codec
      = pb::FieldCodec.ForString(74);
  private readonly pbc::RepeatedField<string> history_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<string> History {
    get { return history_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as DurableOrchestrationStatus);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(DurableOrchestrationStatus other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (Id != other.Id) return false;
    if (!object.Equals(CreatedTime, other.CreatedTime)) return false;
    if (!object.Equals(LastUpdatedTime, other.LastUpdatedTime)) return false;
    if (Input != other.Input) return false;
    if (Output != other.Output) return false;
    if(!runtimeStatus_.Equals(other.runtimeStatus_)) return false;
    if (CustomStatus != other.CustomStatus) return false;
    if(!history_.Equals(other.history_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    if (createdTime_ != null) hash ^= CreatedTime.GetHashCode();
    if (lastUpdatedTime_ != null) hash ^= LastUpdatedTime.GetHashCode();
    if (Input.Length != 0) hash ^= Input.GetHashCode();
    if (Output.Length != 0) hash ^= Output.GetHashCode();
    hash ^= runtimeStatus_.GetHashCode();
    if (CustomStatus.Length != 0) hash ^= CustomStatus.GetHashCode();
    hash ^= history_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Id.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Id);
    }
    if (createdTime_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(CreatedTime);
    }
    if (lastUpdatedTime_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(LastUpdatedTime);
    }
    if (Input.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Input);
    }
    if (Output.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Output);
    }
    runtimeStatus_.WriteTo(output, _repeated_runtimeStatus_codec);
    if (CustomStatus.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(CustomStatus);
    }
    history_.WriteTo(output, _repeated_history_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    if (createdTime_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreatedTime);
    }
    if (lastUpdatedTime_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastUpdatedTime);
    }
    if (Input.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Input);
    }
    if (Output.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Output);
    }
    size += runtimeStatus_.CalculateSize(_repeated_runtimeStatus_codec);
    if (CustomStatus.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CustomStatus);
    }
    size += history_.CalculateSize(_repeated_history_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(DurableOrchestrationStatus other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    if (other.createdTime_ != null) {
      if (createdTime_ == null) {
        CreatedTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      CreatedTime.MergeFrom(other.CreatedTime);
    }
    if (other.lastUpdatedTime_ != null) {
      if (lastUpdatedTime_ == null) {
        LastUpdatedTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      LastUpdatedTime.MergeFrom(other.LastUpdatedTime);
    }
    if (other.Input.Length != 0) {
      Input = other.Input;
    }
    if (other.Output.Length != 0) {
      Output = other.Output;
    }
    runtimeStatus_.Add(other.runtimeStatus_);
    if (other.CustomStatus.Length != 0) {
      CustomStatus = other.CustomStatus;
    }
    history_.Add(other.history_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 18: {
          Id = input.ReadString();
          break;
        }
        case 26: {
          if (createdTime_ == null) {
            CreatedTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(CreatedTime);
          break;
        }
        case 34: {
          if (lastUpdatedTime_ == null) {
            LastUpdatedTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(LastUpdatedTime);
          break;
        }
        case 42: {
          Input = input.ReadString();
          break;
        }
        case 50: {
          Output = input.ReadString();
          break;
        }
        case 58: {
          runtimeStatus_.AddEntriesFrom(input, _repeated_runtimeStatus_codec);
          break;
        }
        case 66: {
          CustomStatus = input.ReadString();
          break;
        }
        case 74: {
          history_.AddEntriesFrom(input, _repeated_history_codec);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
