#pragma warning disable
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DurableRpc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from DurableRpc.proto</summary>
public static partial class DurableRpcReflection {

  #region Descriptor
  /// <summary>File descriptor for DurableRpc.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DurableRpcReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChBEdXJhYmxlUnBjLnByb3RvGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1w",
          "LnByb3RvIo4CCg1DbGllbnRSZXF1ZXN0EiEKBHR5cGUYASABKA4yEy5DbGll",
          "bnRSZXF1ZXN0LlR5cGUSJgoEYXJncxgCIAMoCzIYLkNsaWVudFJlcXVlc3Qu",
          "QXJnc0VudHJ5Eh0KBmNvbmZpZxgDIAEoCzINLkNsaWVudENvbmZpZxo+CglB",
          "cmdzRW50cnkSCwoDa2V5GAEgASgJEiAKBXZhbHVlGAIgASgLMhEuRHVyYWJs",
          "ZVR5cGVkRGF0YToCOAEiUwoEVHlwZRIKCgZTdGF0dXMQABIKCgZDcmVhdGUQ",
          "ARINCglTZW5kRXZlbnQQAhINCglUZXJtaW5hdGUQAxIKCgZSZXdpbmQQBBIJ",
          "CgVQdXJnZRAFIo0BCg5DbGllbnRSZXNwb25zZRImCgZyZXN1bHQYASABKA4y",
          "Fi5DbGllbnRSZXNwb25zZS5SZXN1bHQSDQoFZXJyb3IYAiABKAwSHwoEZGF0",
          "YRgDIAEoCzIRLkR1cmFibGVUeXBlZERhdGEiIwoGUmVzdWx0Eg0KCUNvbXBs",
          "ZXRlZBAAEgoKBkZhaWxlZBABIv0BChBEdXJhYmxlVHlwZWREYXRhEhAKBnN0",
          "cmluZxgBIAEoCUgAEg4KBGpzb24YAiABKAlIABIPCgVieXRlcxgDIAEoDEgA",
          "Eg4KBGJvb2wYBCABKAhIABINCgNpbnQYBSABKBJIABIvCgl0aW1lc3RhbXAY",
          "BiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSAASLgoRY29sbGVj",
          "dGlvbl9zdHJpbmcYByABKAsyES5TdHJpbmdDb2xsZWN0aW9uSAASLgoRY29s",
          "bGVjdGlvbl9zdGF0dXMYCCABKAsyES5TdGF0dXNDb2xsZWN0aW9uSABCBgoE",
          "ZGF0YSIjChBTdHJpbmdDb2xsZWN0aW9uEg8KB3N0cmluZ3MYASADKAkiWAoQ",
          "U3RhdHVzQ29sbGVjdGlvbhIpCghzdGF0dXNlcxgBIAMoCzIXLlJwY09yY2hl",
          "c3RyYXRpb25TdGF0dXMSGQoRY29udGludWF0aW9uVG9rZW4YAiABKAki9gEK",
          "FlJwY09yY2hlc3RyYXRpb25TdGF0dXMSDAoEbmFtZRgBIAEoCRIKCgJpZBgC",
          "IAEoCRIvCgtjcmVhdGVkVGltZRgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5U",
          "aW1lc3RhbXASMwoPbGFzdFVwZGF0ZWRUaW1lGAQgASgLMhouZ29vZ2xlLnBy",
          "b3RvYnVmLlRpbWVzdGFtcBINCgVpbnB1dBgFIAEoCRIOCgZvdXRwdXQYBiAB",
          "KAkSFgoOcnVudGltZV9zdGF0dXMYByABKAkSFAoMY3VzdG9tU3RhdHVzGAgg",
          "ASgJEg8KB2hpc3RvcnkYCSADKAkiNAoMQ2xpZW50Q29uZmlnEhAKCHRhc2tf",
          "aHViGAEgASgJEhIKCmNvbm5lY3Rpb24YAiABKAkyQgoKRHVyYWJsZVJwYxI0",
          "Cg9DbGllbnRPcGVyYXRpb24SDi5DbGllbnRSZXF1ZXN0Gg8uQ2xpZW50UmVz",
          "cG9uc2UiAGIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ClientRequest), global::ClientRequest.Parser, new[]{ "Type", "Args", "Config" }, null, new[]{ typeof(global::ClientRequest.Types.Type) }, new pbr::GeneratedClrTypeInfo[] { null, }),
          new pbr::GeneratedClrTypeInfo(typeof(global::ClientResponse), global::ClientResponse.Parser, new[]{ "Result", "Error", "Data" }, null, new[]{ typeof(global::ClientResponse.Types.Result) }, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::DurableTypedData), global::DurableTypedData.Parser, new[]{ "String", "Json", "Bytes", "Bool", "Int", "Timestamp", "CollectionString", "CollectionStatus" }, new[]{ "Data" }, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::StringCollection), global::StringCollection.Parser, new[]{ "Strings" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::StatusCollection), global::StatusCollection.Parser, new[]{ "Statuses", "ContinuationToken" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RpcOrchestrationStatus), global::RpcOrchestrationStatus.Parser, new[]{ "Name", "Id", "CreatedTime", "LastUpdatedTime", "Input", "Output", "RuntimeStatus", "CustomStatus", "History" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ClientConfig), global::ClientConfig.Parser, new[]{ "TaskHub", "Connection" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ClientRequest : pb::IMessage<ClientRequest> {
  private static readonly pb::MessageParser<ClientRequest> _parser = new pb::MessageParser<ClientRequest>(() => new ClientRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ClientRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DurableRpcReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientRequest(ClientRequest other) : this() {
    type_ = other.type_;
    args_ = other.args_.Clone();
    config_ = other.config_ != null ? other.config_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientRequest Clone() {
    return new ClientRequest(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::ClientRequest.Types.Type type_ = 0;
  /// <summary>
  /// Type of client request.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ClientRequest.Types.Type Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "args" field.</summary>
  public const int ArgsFieldNumber = 2;
  private static readonly pbc::MapField<string, global::DurableTypedData>.Codec _map_args_codec
      = new pbc::MapField<string, global::DurableTypedData>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForMessage(18, global::DurableTypedData.Parser), 18);
  private readonly pbc::MapField<string, global::DurableTypedData> args_ = new pbc::MapField<string, global::DurableTypedData>();
  /// <summary>
  /// Request arguments
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::MapField<string, global::DurableTypedData> Args {
    get { return args_; }
  }

  /// <summary>Field number for the "config" field.</summary>
  public const int ConfigFieldNumber = 3;
  private global::ClientConfig config_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ClientConfig Config {
    get { return config_; }
    set {
      config_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ClientRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ClientRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (!Args.Equals(other.Args)) return false;
    if (!object.Equals(Config, other.Config)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != 0) hash ^= Type.GetHashCode();
    hash ^= Args.GetHashCode();
    if (config_ != null) hash ^= Config.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Type != 0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    args_.WriteTo(output, _map_args_codec);
    if (config_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Config);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Type != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    size += args_.CalculateSize(_map_args_codec);
    if (config_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Config);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ClientRequest other) {
    if (other == null) {
      return;
    }
    if (other.Type != 0) {
      Type = other.Type;
    }
    args_.Add(other.args_);
    if (other.config_ != null) {
      if (config_ == null) {
        Config = new global::ClientConfig();
      }
      Config.MergeFrom(other.Config);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::ClientRequest.Types.Type) input.ReadEnum();
          break;
        }
        case 18: {
          args_.AddEntriesFrom(input, _map_args_codec);
          break;
        }
        case 26: {
          if (config_ == null) {
            Config = new global::ClientConfig();
          }
          input.ReadMessage(Config);
          break;
        }
      }
    }
  }

  #region Nested types
  /// <summary>Container for nested types declared in the ClientRequest message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public enum Type {
      [pbr::OriginalName("Status")] Status = 0,
      [pbr::OriginalName("Create")] Create = 1,
      [pbr::OriginalName("SendEvent")] SendEvent = 2,
      [pbr::OriginalName("Terminate")] Terminate = 3,
      [pbr::OriginalName("Rewind")] Rewind = 4,
      [pbr::OriginalName("Purge")] Purge = 5,
    }

  }
  #endregion

}

public sealed partial class ClientResponse : pb::IMessage<ClientResponse> {
  private static readonly pb::MessageParser<ClientResponse> _parser = new pb::MessageParser<ClientResponse>(() => new ClientResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ClientResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DurableRpcReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientResponse(ClientResponse other) : this() {
    result_ = other.result_;
    error_ = other.error_;
    data_ = other.data_ != null ? other.data_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientResponse Clone() {
    return new ClientResponse(this);
  }

  /// <summary>Field number for the "result" field.</summary>
  public const int ResultFieldNumber = 1;
  private global::ClientResponse.Types.Result result_ = 0;
  /// <summary>
  /// 
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ClientResponse.Types.Result Result {
    get { return result_; }
    set {
      result_ = value;
    }
  }

  /// <summary>Field number for the "error" field.</summary>
  public const int ErrorFieldNumber = 2;
  private pb::ByteString error_ = pb::ByteString.Empty;
  /// <summary>
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Error {
    get { return error_; }
    set {
      error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 3;
  private global::DurableTypedData data_;
  /// <summary>
  /// TODO: not bytes
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::DurableTypedData Data {
    get { return data_; }
    set {
      data_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ClientResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ClientResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Result != other.Result) return false;
    if (Error != other.Error) return false;
    if (!object.Equals(Data, other.Data)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Result != 0) hash ^= Result.GetHashCode();
    if (Error.Length != 0) hash ^= Error.GetHashCode();
    if (data_ != null) hash ^= Data.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Result != 0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Result);
    }
    if (Error.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(Error);
    }
    if (data_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Result != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
    }
    if (Error.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Error);
    }
    if (data_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ClientResponse other) {
    if (other == null) {
      return;
    }
    if (other.Result != 0) {
      Result = other.Result;
    }
    if (other.Error.Length != 0) {
      Error = other.Error;
    }
    if (other.data_ != null) {
      if (data_ == null) {
        Data = new global::DurableTypedData();
      }
      Data.MergeFrom(other.Data);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Result = (global::ClientResponse.Types.Result) input.ReadEnum();
          break;
        }
        case 18: {
          Error = input.ReadBytes();
          break;
        }
        case 26: {
          if (data_ == null) {
            Data = new global::DurableTypedData();
          }
          input.ReadMessage(Data);
          break;
        }
      }
    }
  }

  #region Nested types
  /// <summary>Container for nested types declared in the ClientResponse message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public enum Result {
      [pbr::OriginalName("Completed")] Completed = 0,
      [pbr::OriginalName("Failed")] Failed = 1,
    }

  }
  #endregion

}

/// <summary>
/// Used to encapsulate data which could be a variety of types
/// </summary>
public sealed partial class DurableTypedData : pb::IMessage<DurableTypedData> {
  private static readonly pb::MessageParser<DurableTypedData> _parser = new pb::MessageParser<DurableTypedData>(() => new DurableTypedData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<DurableTypedData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DurableRpcReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DurableTypedData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DurableTypedData(DurableTypedData other) : this() {
    switch (other.DataCase) {
      case DataOneofCase.String:
        String = other.String;
        break;
      case DataOneofCase.Json:
        Json = other.Json;
        break;
      case DataOneofCase.Bytes:
        Bytes = other.Bytes;
        break;
      case DataOneofCase.Bool:
        Bool = other.Bool;
        break;
      case DataOneofCase.Int:
        Int = other.Int;
        break;
      case DataOneofCase.Timestamp:
        Timestamp = other.Timestamp.Clone();
        break;
      case DataOneofCase.CollectionString:
        CollectionString = other.CollectionString.Clone();
        break;
      case DataOneofCase.CollectionStatus:
        CollectionStatus = other.CollectionStatus.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DurableTypedData Clone() {
    return new DurableTypedData(this);
  }

  /// <summary>Field number for the "string" field.</summary>
  public const int StringFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string String {
    get { return dataCase_ == DataOneofCase.String ? (string) data_ : ""; }
    set {
      data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      dataCase_ = DataOneofCase.String;
    }
  }

  /// <summary>Field number for the "json" field.</summary>
  public const int JsonFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Json {
    get { return dataCase_ == DataOneofCase.Json ? (string) data_ : ""; }
    set {
      data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      dataCase_ = DataOneofCase.Json;
    }
  }

  /// <summary>Field number for the "bytes" field.</summary>
  public const int BytesFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Bytes {
    get { return dataCase_ == DataOneofCase.Bytes ? (pb::ByteString) data_ : pb::ByteString.Empty; }
    set {
      data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      dataCase_ = DataOneofCase.Bytes;
    }
  }

  /// <summary>Field number for the "bool" field.</summary>
  public const int BoolFieldNumber = 4;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Bool {
    get { return dataCase_ == DataOneofCase.Bool ? (bool) data_ : false; }
    set {
      data_ = value;
      dataCase_ = DataOneofCase.Bool;
    }
  }

  /// <summary>Field number for the "int" field.</summary>
  public const int IntFieldNumber = 5;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long Int {
    get { return dataCase_ == DataOneofCase.Int ? (long) data_ : 0L; }
    set {
      data_ = value;
      dataCase_ = DataOneofCase.Int;
    }
  }

  /// <summary>Field number for the "timestamp" field.</summary>
  public const int TimestampFieldNumber = 6;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
    get { return dataCase_ == DataOneofCase.Timestamp ? (global::Google.Protobuf.WellKnownTypes.Timestamp) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Timestamp;
    }
  }

  /// <summary>Field number for the "collection_string" field.</summary>
  public const int CollectionStringFieldNumber = 7;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::StringCollection CollectionString {
    get { return dataCase_ == DataOneofCase.CollectionString ? (global::StringCollection) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.CollectionString;
    }
  }

  /// <summary>Field number for the "collection_status" field.</summary>
  public const int CollectionStatusFieldNumber = 8;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::StatusCollection CollectionStatus {
    get { return dataCase_ == DataOneofCase.CollectionStatus ? (global::StatusCollection) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.CollectionStatus;
    }
  }

  private object data_;
  /// <summary>Enum of possible cases for the "data" oneof.</summary>
  public enum DataOneofCase {
    None = 0,
    String = 1,
    Json = 2,
    Bytes = 3,
    Bool = 4,
    Int = 5,
    Timestamp = 6,
    CollectionString = 7,
    CollectionStatus = 8,
  }
  private DataOneofCase dataCase_ = DataOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DataOneofCase DataCase {
    get { return dataCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearData() {
    dataCase_ = DataOneofCase.None;
    data_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as DurableTypedData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(DurableTypedData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (String != other.String) return false;
    if (Json != other.Json) return false;
    if (Bytes != other.Bytes) return false;
    if (Bool != other.Bool) return false;
    if (Int != other.Int) return false;
    if (!object.Equals(Timestamp, other.Timestamp)) return false;
    if (!object.Equals(CollectionString, other.CollectionString)) return false;
    if (!object.Equals(CollectionStatus, other.CollectionStatus)) return false;
    if (DataCase != other.DataCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (dataCase_ == DataOneofCase.String) hash ^= String.GetHashCode();
    if (dataCase_ == DataOneofCase.Json) hash ^= Json.GetHashCode();
    if (dataCase_ == DataOneofCase.Bytes) hash ^= Bytes.GetHashCode();
    if (dataCase_ == DataOneofCase.Bool) hash ^= Bool.GetHashCode();
    if (dataCase_ == DataOneofCase.Int) hash ^= Int.GetHashCode();
    if (dataCase_ == DataOneofCase.Timestamp) hash ^= Timestamp.GetHashCode();
    if (dataCase_ == DataOneofCase.CollectionString) hash ^= CollectionString.GetHashCode();
    if (dataCase_ == DataOneofCase.CollectionStatus) hash ^= CollectionStatus.GetHashCode();
    hash ^= (int) dataCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (dataCase_ == DataOneofCase.String) {
      output.WriteRawTag(10);
      output.WriteString(String);
    }
    if (dataCase_ == DataOneofCase.Json) {
      output.WriteRawTag(18);
      output.WriteString(Json);
    }
    if (dataCase_ == DataOneofCase.Bytes) {
      output.WriteRawTag(26);
      output.WriteBytes(Bytes);
    }
    if (dataCase_ == DataOneofCase.Bool) {
      output.WriteRawTag(32);
      output.WriteBool(Bool);
    }
    if (dataCase_ == DataOneofCase.Int) {
      output.WriteRawTag(40);
      output.WriteSInt64(Int);
    }
    if (dataCase_ == DataOneofCase.Timestamp) {
      output.WriteRawTag(50);
      output.WriteMessage(Timestamp);
    }
    if (dataCase_ == DataOneofCase.CollectionString) {
      output.WriteRawTag(58);
      output.WriteMessage(CollectionString);
    }
    if (dataCase_ == DataOneofCase.CollectionStatus) {
      output.WriteRawTag(66);
      output.WriteMessage(CollectionStatus);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (dataCase_ == DataOneofCase.String) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(String);
    }
    if (dataCase_ == DataOneofCase.Json) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Json);
    }
    if (dataCase_ == DataOneofCase.Bytes) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Bytes);
    }
    if (dataCase_ == DataOneofCase.Bool) {
      size += 1 + 1;
    }
    if (dataCase_ == DataOneofCase.Int) {
      size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Int);
    }
    if (dataCase_ == DataOneofCase.Timestamp) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
    }
    if (dataCase_ == DataOneofCase.CollectionString) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(CollectionString);
    }
    if (dataCase_ == DataOneofCase.CollectionStatus) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(CollectionStatus);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(DurableTypedData other) {
    if (other == null) {
      return;
    }
    switch (other.DataCase) {
      case DataOneofCase.String:
        String = other.String;
        break;
      case DataOneofCase.Json:
        Json = other.Json;
        break;
      case DataOneofCase.Bytes:
        Bytes = other.Bytes;
        break;
      case DataOneofCase.Bool:
        Bool = other.Bool;
        break;
      case DataOneofCase.Int:
        Int = other.Int;
        break;
      case DataOneofCase.Timestamp:
        if (Timestamp == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
        break;
      case DataOneofCase.CollectionString:
        if (CollectionString == null) {
          CollectionString = new global::StringCollection();
        }
        CollectionString.MergeFrom(other.CollectionString);
        break;
      case DataOneofCase.CollectionStatus:
        if (CollectionStatus == null) {
          CollectionStatus = new global::StatusCollection();
        }
        CollectionStatus.MergeFrom(other.CollectionStatus);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          String = input.ReadString();
          break;
        }
        case 18: {
          Json = input.ReadString();
          break;
        }
        case 26: {
          Bytes = input.ReadBytes();
          break;
        }
        case 32: {
          Bool = input.ReadBool();
          break;
        }
        case 40: {
          Int = input.ReadSInt64();
          break;
        }
        case 50: {
          global::Google.Protobuf.WellKnownTypes.Timestamp subBuilder = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          if (dataCase_ == DataOneofCase.Timestamp) {
            subBuilder.MergeFrom(Timestamp);
          }
          input.ReadMessage(subBuilder);
          Timestamp = subBuilder;
          break;
        }
        case 58: {
          global::StringCollection subBuilder = new global::StringCollection();
          if (dataCase_ == DataOneofCase.CollectionString) {
            subBuilder.MergeFrom(CollectionString);
          }
          input.ReadMessage(subBuilder);
          CollectionString = subBuilder;
          break;
        }
        case 66: {
          global::StatusCollection subBuilder = new global::StatusCollection();
          if (dataCase_ == DataOneofCase.CollectionStatus) {
            subBuilder.MergeFrom(CollectionStatus);
          }
          input.ReadMessage(subBuilder);
          CollectionStatus = subBuilder;
          break;
        }
      }
    }
  }

}

/// <summary>
/// Used to encapsulate collection string
/// </summary>
public sealed partial class StringCollection : pb::IMessage<StringCollection> {
  private static readonly pb::MessageParser<StringCollection> _parser = new pb::MessageParser<StringCollection>(() => new StringCollection());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<StringCollection> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DurableRpcReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public StringCollection() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public StringCollection(StringCollection other) : this() {
    strings_ = other.strings_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public StringCollection Clone() {
    return new StringCollection(this);
  }

  /// <summary>Field number for the "strings" field.</summary>
  public const int StringsFieldNumber = 1;
  private static readonly pb::FieldCodec<string> _repeated_strings_codec
      = pb::FieldCodec.ForString(10);
  private readonly pbc::RepeatedField<string> strings_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<string> Strings {
    get { return strings_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as StringCollection);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(StringCollection other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!strings_.Equals(other.strings_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= strings_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    strings_.WriteTo(output, _repeated_strings_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += strings_.CalculateSize(_repeated_strings_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(StringCollection other) {
    if (other == null) {
      return;
    }
    strings_.Add(other.strings_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          strings_.AddEntriesFrom(input, _repeated_strings_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class StatusCollection : pb::IMessage<StatusCollection> {
  private static readonly pb::MessageParser<StatusCollection> _parser = new pb::MessageParser<StatusCollection>(() => new StatusCollection());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<StatusCollection> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DurableRpcReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public StatusCollection() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public StatusCollection(StatusCollection other) : this() {
    statuses_ = other.statuses_.Clone();
    continuationToken_ = other.continuationToken_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public StatusCollection Clone() {
    return new StatusCollection(this);
  }

  /// <summary>Field number for the "statuses" field.</summary>
  public const int StatusesFieldNumber = 1;
  private static readonly pb::FieldCodec<global::RpcOrchestrationStatus> _repeated_statuses_codec
      = pb::FieldCodec.ForMessage(10, global::RpcOrchestrationStatus.Parser);
  private readonly pbc::RepeatedField<global::RpcOrchestrationStatus> statuses_ = new pbc::RepeatedField<global::RpcOrchestrationStatus>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::RpcOrchestrationStatus> Statuses {
    get { return statuses_; }
  }

  /// <summary>Field number for the "continuationToken" field.</summary>
  public const int ContinuationTokenFieldNumber = 2;
  private string continuationToken_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string ContinuationToken {
    get { return continuationToken_; }
    set {
      continuationToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as StatusCollection);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(StatusCollection other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!statuses_.Equals(other.statuses_)) return false;
    if (ContinuationToken != other.ContinuationToken) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= statuses_.GetHashCode();
    if (ContinuationToken.Length != 0) hash ^= ContinuationToken.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    statuses_.WriteTo(output, _repeated_statuses_codec);
    if (ContinuationToken.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(ContinuationToken);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += statuses_.CalculateSize(_repeated_statuses_codec);
    if (ContinuationToken.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ContinuationToken);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(StatusCollection other) {
    if (other == null) {
      return;
    }
    statuses_.Add(other.statuses_);
    if (other.ContinuationToken.Length != 0) {
      ContinuationToken = other.ContinuationToken;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          statuses_.AddEntriesFrom(input, _repeated_statuses_codec);
          break;
        }
        case 18: {
          ContinuationToken = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class RpcOrchestrationStatus : pb::IMessage<RpcOrchestrationStatus> {
  private static readonly pb::MessageParser<RpcOrchestrationStatus> _parser = new pb::MessageParser<RpcOrchestrationStatus>(() => new RpcOrchestrationStatus());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<RpcOrchestrationStatus> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DurableRpcReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RpcOrchestrationStatus() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RpcOrchestrationStatus(RpcOrchestrationStatus other) : this() {
    name_ = other.name_;
    id_ = other.id_;
    createdTime_ = other.createdTime_ != null ? other.createdTime_.Clone() : null;
    lastUpdatedTime_ = other.lastUpdatedTime_ != null ? other.lastUpdatedTime_.Clone() : null;
    input_ = other.input_;
    output_ = other.output_;
    runtimeStatus_ = other.runtimeStatus_;
    customStatus_ = other.customStatus_;
    history_ = other.history_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RpcOrchestrationStatus Clone() {
    return new RpcOrchestrationStatus(this);
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 2;
  private string id_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "createdTime" field.</summary>
  public const int CreatedTimeFieldNumber = 3;
  private global::Google.Protobuf.WellKnownTypes.Timestamp createdTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Google.Protobuf.WellKnownTypes.Timestamp CreatedTime {
    get { return createdTime_; }
    set {
      createdTime_ = value;
    }
  }

  /// <summary>Field number for the "lastUpdatedTime" field.</summary>
  public const int LastUpdatedTimeFieldNumber = 4;
  private global::Google.Protobuf.WellKnownTypes.Timestamp lastUpdatedTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Google.Protobuf.WellKnownTypes.Timestamp LastUpdatedTime {
    get { return lastUpdatedTime_; }
    set {
      lastUpdatedTime_ = value;
    }
  }

  /// <summary>Field number for the "input" field.</summary>
  public const int InputFieldNumber = 5;
  private string input_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Input {
    get { return input_; }
    set {
      input_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "output" field.</summary>
  public const int OutputFieldNumber = 6;
  private string output_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Output {
    get { return output_; }
    set {
      output_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "runtime_status" field.</summary>
  public const int RuntimeStatusFieldNumber = 7;
  private string runtimeStatus_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string RuntimeStatus {
    get { return runtimeStatus_; }
    set {
      runtimeStatus_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "customStatus" field.</summary>
  public const int CustomStatusFieldNumber = 8;
  private string customStatus_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string CustomStatus {
    get { return customStatus_; }
    set {
      customStatus_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "history" field.</summary>
  public const int HistoryFieldNumber = 9;
  private static readonly pb::FieldCodec<string> _repeated_history_codec
      = pb::FieldCodec.ForString(74);
  private readonly pbc::RepeatedField<string> history_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<string> History {
    get { return history_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as RpcOrchestrationStatus);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(RpcOrchestrationStatus other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (Id != other.Id) return false;
    if (!object.Equals(CreatedTime, other.CreatedTime)) return false;
    if (!object.Equals(LastUpdatedTime, other.LastUpdatedTime)) return false;
    if (Input != other.Input) return false;
    if (Output != other.Output) return false;
    if (RuntimeStatus != other.RuntimeStatus) return false;
    if (CustomStatus != other.CustomStatus) return false;
    if(!history_.Equals(other.history_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    if (createdTime_ != null) hash ^= CreatedTime.GetHashCode();
    if (lastUpdatedTime_ != null) hash ^= LastUpdatedTime.GetHashCode();
    if (Input.Length != 0) hash ^= Input.GetHashCode();
    if (Output.Length != 0) hash ^= Output.GetHashCode();
    if (RuntimeStatus.Length != 0) hash ^= RuntimeStatus.GetHashCode();
    if (CustomStatus.Length != 0) hash ^= CustomStatus.GetHashCode();
    hash ^= history_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Id.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Id);
    }
    if (createdTime_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(CreatedTime);
    }
    if (lastUpdatedTime_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(LastUpdatedTime);
    }
    if (Input.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Input);
    }
    if (Output.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Output);
    }
    if (RuntimeStatus.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(RuntimeStatus);
    }
    if (CustomStatus.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(CustomStatus);
    }
    history_.WriteTo(output, _repeated_history_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    if (createdTime_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreatedTime);
    }
    if (lastUpdatedTime_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastUpdatedTime);
    }
    if (Input.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Input);
    }
    if (Output.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Output);
    }
    if (RuntimeStatus.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RuntimeStatus);
    }
    if (CustomStatus.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CustomStatus);
    }
    size += history_.CalculateSize(_repeated_history_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(RpcOrchestrationStatus other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    if (other.createdTime_ != null) {
      if (createdTime_ == null) {
        CreatedTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      CreatedTime.MergeFrom(other.CreatedTime);
    }
    if (other.lastUpdatedTime_ != null) {
      if (lastUpdatedTime_ == null) {
        LastUpdatedTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      LastUpdatedTime.MergeFrom(other.LastUpdatedTime);
    }
    if (other.Input.Length != 0) {
      Input = other.Input;
    }
    if (other.Output.Length != 0) {
      Output = other.Output;
    }
    if (other.RuntimeStatus.Length != 0) {
      RuntimeStatus = other.RuntimeStatus;
    }
    if (other.CustomStatus.Length != 0) {
      CustomStatus = other.CustomStatus;
    }
    history_.Add(other.history_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 18: {
          Id = input.ReadString();
          break;
        }
        case 26: {
          if (createdTime_ == null) {
            CreatedTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(CreatedTime);
          break;
        }
        case 34: {
          if (lastUpdatedTime_ == null) {
            LastUpdatedTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(LastUpdatedTime);
          break;
        }
        case 42: {
          Input = input.ReadString();
          break;
        }
        case 50: {
          Output = input.ReadString();
          break;
        }
        case 58: {
          RuntimeStatus = input.ReadString();
          break;
        }
        case 66: {
          CustomStatus = input.ReadString();
          break;
        }
        case 74: {
          history_.AddEntriesFrom(input, _repeated_history_codec);
          break;
        }
      }
    }
  }

}

/// <summary>
/// Information from the client binding
/// </summary>
public sealed partial class ClientConfig : pb::IMessage<ClientConfig> {
  private static readonly pb::MessageParser<ClientConfig> _parser = new pb::MessageParser<ClientConfig>(() => new ClientConfig());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ClientConfig> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DurableRpcReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientConfig() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientConfig(ClientConfig other) : this() {
    taskHub_ = other.taskHub_;
    connection_ = other.connection_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientConfig Clone() {
    return new ClientConfig(this);
  }

  /// <summary>Field number for the "task_hub" field.</summary>
  public const int TaskHubFieldNumber = 1;
  private string taskHub_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string TaskHub {
    get { return taskHub_; }
    set {
      taskHub_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "connection" field.</summary>
  public const int ConnectionFieldNumber = 2;
  private string connection_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Connection {
    get { return connection_; }
    set {
      connection_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ClientConfig);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ClientConfig other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (TaskHub != other.TaskHub) return false;
    if (Connection != other.Connection) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (TaskHub.Length != 0) hash ^= TaskHub.GetHashCode();
    if (Connection.Length != 0) hash ^= Connection.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (TaskHub.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(TaskHub);
    }
    if (Connection.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Connection);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (TaskHub.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskHub);
    }
    if (Connection.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Connection);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ClientConfig other) {
    if (other == null) {
      return;
    }
    if (other.TaskHub.Length != 0) {
      TaskHub = other.TaskHub;
    }
    if (other.Connection.Length != 0) {
      Connection = other.Connection;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          TaskHub = input.ReadString();
          break;
        }
        case 18: {
          Connection = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
