#pragma warning disable
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DurableRpc.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class DurableRpc
{
  static readonly string __ServiceName = "DurableRpc";

  static readonly grpc::Marshaller<global::ClientRequest> __Marshaller_ClientRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ClientRequest.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::ClientResponse> __Marshaller_ClientResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ClientResponse.Parser.ParseFrom);

  static readonly grpc::Method<global::ClientRequest, global::ClientResponse> __Method_ClientOperation = new grpc::Method<global::ClientRequest, global::ClientResponse>(
      grpc::MethodType.Unary,
      __ServiceName,
      "ClientOperation",
      __Marshaller_ClientRequest,
      __Marshaller_ClientResponse);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::DurableRpcReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of DurableRpc</summary>
  public abstract partial class DurableRpcBase
  {
    public virtual global::System.Threading.Tasks.Task<global::ClientResponse> ClientOperation(global::ClientRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for DurableRpc</summary>
  public partial class DurableRpcClient : grpc::ClientBase<DurableRpcClient>
  {
    /// <summary>Creates a new client for DurableRpc</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public DurableRpcClient(grpc::Channel channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for DurableRpc that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public DurableRpcClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected DurableRpcClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected DurableRpcClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::ClientResponse ClientOperation(global::ClientRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return ClientOperation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::ClientResponse ClientOperation(global::ClientRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_ClientOperation, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::ClientResponse> ClientOperationAsync(global::ClientRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return ClientOperationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::ClientResponse> ClientOperationAsync(global::ClientRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_ClientOperation, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override DurableRpcClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new DurableRpcClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(DurableRpcBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_ClientOperation, serviceImpl.ClientOperation).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, DurableRpcBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_ClientOperation, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ClientRequest, global::ClientResponse>(serviceImpl.ClientOperation));
  }

}
#endregion
